/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DAOClass.Form;

import DAOClass.HocVienDAO;
import DAOClass.ModelsClass.HocVien;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Date;
import java.util.List;
import java.util.UUID;

/**
 *
 * @author ADMIN
 */
public class HocVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form HocVienPanel
     */
    private JTable table;
    private DefaultTableModel tableModel;
    private HocVienDAO hocVienDAO;

    public HocVienPanel() {
        setLayout(new BorderLayout());
        hocVienDAO = new HocVienDAO();

        String[] columnNames = {"Mã Học Viên", "Họ Tên", "Ngày Sinh", "Email", "Số Điện Thoại", "Giới Tính", "Trạng Thái"};
        tableModel = new DefaultTableModel(columnNames, 0);
        table = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel();
        JButton btnAdd = new JButton("Thêm");
        JButton btnEdit = new JButton("Sửa");
        JButton btnDelete = new JButton("Xóa");

        btnAdd.addActionListener(e -> addHocVien());
        btnEdit.addActionListener(e -> editHocVien());
        btnDelete.addActionListener(e -> deleteHocVien());

        buttonPanel.add(btnAdd);
        buttonPanel.add(btnEdit);
        buttonPanel.add(btnDelete);
        add(buttonPanel, BorderLayout.SOUTH);

        loadData();
    }

    private void loadData() {
        tableModel.setRowCount(0);
        List<HocVien> list = hocVienDAO.hienThi();
        for (HocVien hv : list) {
            tableModel.addRow(new Object[]{hv.getId(), hv.getHoTen(), hv.getNgaySinh(), hv.getEmail(), hv.getSoDienThoai(), hv.getGioiTinh(), hv.getTrangThai()});
        }
    }

    private void addHocVien() {
        String hoTen = JOptionPane.showInputDialog(this, "Nhập họ tên:");
        String ngaySinh = JOptionPane.showInputDialog(this, "Nhập ngày sinh (YYYY-MM-DD):");
        String email = JOptionPane.showInputDialog(this, "Nhập email:");
        String soDienThoai = JOptionPane.showInputDialog(this, "Nhập số điện thoại:");
        String gioiTinh = JOptionPane.showInputDialog(this, "Nhập giới tính (Nam/Nữ):");
        int trangThai = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập trạng thái (0/1):"));

        HocVien hv = new HocVien(UUID.randomUUID(), hoTen, ngaySinh, email, soDienThoai, gioiTinh, trangThai);
        if (hocVienDAO.themHocVien(hv)) {
            loadData();
        }
    }

    private void editHocVien() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên để sửa.");
            return;
        }

        UUID id = UUID.fromString(tableModel.getValueAt(selectedRow, 0).toString());
        String hoTen = JOptionPane.showInputDialog(this, "Nhập họ tên:", tableModel.getValueAt(selectedRow, 1));
        String ngaySinh = JOptionPane.showInputDialog(this, "Nhập ngày sinh:", tableModel.getValueAt(selectedRow, 2));
        String email = JOptionPane.showInputDialog(this, "Nhập email:", tableModel.getValueAt(selectedRow, 3));
        String soDienThoai = JOptionPane.showInputDialog(this, "Nhập số điện thoại:", tableModel.getValueAt(selectedRow, 4));
        String gioiTinh = JOptionPane.showInputDialog(this, "Nhập giới tính:", tableModel.getValueAt(selectedRow, 5));
        int trangThai = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập trạng thái:", tableModel.getValueAt(selectedRow, 6)));

        HocVien hv = new HocVien(id, hoTen, ngaySinh, email, soDienThoai, gioiTinh, trangThai);
        if (hocVienDAO.suaHocVien(hv)) {
            loadData();
        }
    }

    private void deleteHocVien() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên để xóa.");
            return;
        }

        UUID id = UUID.fromString(tableModel.getValueAt(selectedRow, 0).toString());
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa học viên này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (hocVienDAO.xoaHocVien(id)) {
                loadData();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
