/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DAOClass.Form;
import DAOClass.ModelsClass.TaiKhoan;
import DAOClass.TaiKhoanDAO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;
import java.util.UUID;
/**
 *
 * @author ADMIN
 */
public class TaiKhoanPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaiKhoanPanel
     */
    private JTable table;
    private DefaultTableModel tableModel;
    private TaiKhoanDAO taiKhoanDAO;

    public TaiKhoanPanel() {
        setLayout(new BorderLayout());
        taiKhoanDAO = new TaiKhoanDAO();

        String[] columnNames = {"ID Đăng Nhập", "Mật Khẩu", "Email"};
        tableModel = new DefaultTableModel(columnNames, 0);
        table = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel();
        JButton btnAdd = new JButton("Thêm");
        JButton btnEdit = new JButton("Sửa");
        JButton btnDelete = new JButton("Xóa");

        btnAdd.addActionListener(e -> addTaiKhoan());
        btnEdit.addActionListener(e -> editTaiKhoan());
        btnDelete.addActionListener(e -> deleteTaiKhoan());

        buttonPanel.add(btnAdd);
        buttonPanel.add(btnEdit);
        buttonPanel.add(btnDelete);
        add(buttonPanel, BorderLayout.SOUTH);

        loadData();
    }
    
    private void loadData() {
        tableModel.setRowCount(0);
        List<TaiKhoan> list = taiKhoanDAO.hienThi();
        for (TaiKhoan tk : list) {
            tableModel.addRow(new Object[]{tk.getId(), tk.getMk(), tk.getEmail()});
        }
    }

    private void addTaiKhoan() {
        String matKhau = JOptionPane.showInputDialog(this, "Nhập mật khẩu:");
        String email = JOptionPane.showInputDialog(this, "Nhập email:");

        if (matKhau == null || email == null) {
            return;
        }

        TaiKhoan tk = new TaiKhoan(UUID.randomUUID(), matKhau, email);
        if (taiKhoanDAO.themTaiKhoan(tk)) {
            loadData();
        }
    }

    private void editTaiKhoan() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản để sửa.");
            return;
        }

        UUID id = UUID.fromString(tableModel.getValueAt(selectedRow, 0).toString());
        String matKhau = JOptionPane.showInputDialog(this, "Nhập mật khẩu:", tableModel.getValueAt(selectedRow, 1));
        String email = JOptionPane.showInputDialog(this, "Nhập email:", tableModel.getValueAt(selectedRow, 2));

        if (matKhau != null && email != null) {
            TaiKhoan tk = new TaiKhoan(id, matKhau, email);
            if (taiKhoanDAO.suaTaiKhoan(tk)) {
                loadData();
            }
        }
    }

    private void deleteTaiKhoan() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản để xóa.");
            return;
        }

        UUID id = UUID.fromString(tableModel.getValueAt(selectedRow, 0).toString());
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa tài khoản này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (taiKhoanDAO.xoaTaiKhoan(id)) {
                loadData();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
