Create database ABC;
Use ABC

CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    UserName NVARCHAR(50) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    Password NVARCHAR(100) NOT NULL,
    Role NVARCHAR(20) NOT NULL
);

CREATE TABLE PhanLoai (
    CategoryID INT PRIMARY KEY IDENTITY(1,1),
    CategoryName NVARCHAR(50) NOT NULL
);

CREATE TABLE Sach (
    BookID INT PRIMARY KEY IDENTITY(1,1),
    BookName NVARCHAR(100) NOT NULL,
    Author NVARCHAR(100),
    CategoryID INT NOT NULL,
    Quantity INT DEFAULT 0,
    FOREIGN KEY (CategoryID) REFERENCES PhanLoai(CategoryID)
);

CREATE TABLE MuonSach (
    BorrowID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT NOT NULL,
    BookID INT NOT NULL,
    BorrowDate DATE DEFAULT GETDATE(),
    DueDate DATE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (BookID) REFERENCES Sach(BookID)
);

CREATE TABLE TraSach (
    ReturnID INT PRIMARY KEY IDENTITY(1,1),
    BorrowID INT NOT NULL,
    ReturnDate DATE DEFAULT GETDATE(),
    FOREIGN KEY (BorrowID) REFERENCES MuonSach(BorrowID)
);

CREATE TABLE ThongBao (
    NotificationID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT NOT NULL,
    Content NVARCHAR(255) NOT NULL,
    SendDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);